### ISSUE TITLE
Final step "bitbake core-image-full-cmdline" failed due to file permissions.

### ISSUE THREAD

**Issue by viveky1794** [Munawar-git/YoctoTutorials#2]
`
poky/build on  kirkstone took 7s 
❯ **bitbake core-image-full-cmdline**
WARNING: Host distribution "ubuntu-24.04" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Loading cache: 100% |                                                                                 | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |################################################################################| Time: 0:00:25
Parsing of 883 .bb files complete (0 cached, 883 parsed). 1644 targets, 63 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "2.0.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-24.04"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "beaglebone-yocto"
DISTRO               = "poky"
DISTRO_VERSION       = "4.0.21"
TUNE_FEATURES        = "arm vfp cortexa8 neon callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            
meta-yocto-bsp       = "kirkstone:4cdc553814640851cce85f84ee9c0b58646cd33b"

NOTE: Fetching uninative binary shim http://downloads.yoctoproject.org/releases/uninative/4.4/x86_64-nativesdk-libc-4.4.tar.xz;sha256sum=d81c54284be2bb886931fc87281d58177a2cd381cf99d1981f8923039a72a302 (will check PREMIRRORS first)
Initialising tasks: 100% |#############################################################################| Time: 0:00:06
Sstate summary: Wanted 1697 Local 0 Mirrors 0 Missed 1697 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
ERROR: PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ninja/BBB/yocto_tutorial/poky/bitbake/bin/bitbake-worker", line 268, in child
    bb.utils.disable_network(uid, gid)
  File "/home/ninja/BBB/yocto_tutorial/poky/bitbake/lib/bb/utils.py", line 1653, in disable_network
    with open("/proc/self/uid_map", "w") as f:
PermissionError: [Errno 1] Operation not permitted

ERROR: Task (/home/ninja/BBB/yocto_tutorial/poky/meta/recipes-devtools/gcc/gcc-source_11.4.bb:do_rm_work) failed with exit code '1'
ERROR: PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ninja/BBB/yocto_tutorial/poky/bitbake/bin/bitbake-worker", line 268, in child
    bb.utils.disable_network(uid, gid)
  File "/home/ninja/BBB/yocto_tutorial/poky/bitbake/lib/bb/utils.py", line 1653, in disable_network
    with open("/proc/self/uid_map", "w") as f:
PermissionError: [Errno 1] Operation not permitted

ERROR: Task (/home/ninja/BBB/yocto_tutorial/poky/meta/recipes-kernel/linux/linux-yocto_5.15.bb:do_rm_work) failed with exit code '1'
NOTE: Tasks Summary: Attempted 9 tasks of which 0 didn't need to be rerun and 2 failed.

Summary: 2 tasks failed:
  /home/ninja/BBB/yocto_tutorial/poky/meta/recipes-devtools/gcc/gcc-source_11.4.bb:do_rm_work
  /home/ninja/BBB/yocto_tutorial/poky/meta/recipes-kernel/linux/linux-yocto_5.15.bb:do_rm_work
Summary: There was 1 WARNING message.
Summary: There were 2 ERROR messages, returning a non-zero exit code.

poky/build on  kirkstone took 46s 
❯ 
`

**Comment by Munawar-git** [comment]
Use Ubuntu 22.04 or previous one. Yocto is not tested on 24.04 that's why you are getting this error.

**Comment by viveky1794** [comment]
Thanks
Issue got resolve.
