### ISSUE TITLE
Login prompt is not taking keyboard input.

### ISSUE THREAD

**Issue by viveky1794** [Munawar-git/YoctoTutorials#4]
`U-Boot SPL 2018.09-00002-g0b54a51eee (Sep 10 2018 - 19:41:39 -0500)
Trying to boot from MMC2
Loading Environment from EXT4... 
** Unable to use mmc 0:1 for loading the env **

U-Boot 2018.09-00002-g0b54a51eee (Sep 10 2018 - 19:41:39 -0500), Build: jenkins-github_Bootloader-Builder-65

CPU  : AM335X-GP rev 2.1
I2C:   ready
DRAM:  512 MiB
No match for driver 'omap_hsmmc'
No match for driver 'omap_hsmmc'
Some drivers were not found
Reset Source: Global external warm reset has occurred.
Reset Source: Power-on reset has occurred.
RTC 32KCLK Source: External.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Loading Environment from EXT4... 
** Unable to use mmc 0:1 for loading the env **
Board: BeagleBone Black
<ethaddr> not set. Validating first E-fuse MAC
BeagleBone Black:
BeagleBone: cape eeprom: i2c_probe: 0x54:
BeagleBone: cape eeprom: i2c_probe: 0x55:
BeagleBone: cape eeprom: i2c_probe: 0x56:
BeagleBone: cape eeprom: i2c_probe: 0x57:
Net:   eth0: MII MODE
cpsw, usb_ether
Press SPACE to abort autoboot in 2 seconds
board_name=[A335BNLT] ...
board_rev=[00C0] ...
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found /extlinux/extlinux.conf
Retrieving file: /extlinux/extlinux.conf
119 bytes read in 2 ms (57.6 KiB/s)
1:      Yocto
Retrieving file: /uImage
7888360 bytes read in 494 ms (15.2 MiB/s)
append: root=PARTUUID=a607f020-02 rootwait console=ttyS0,115200
Retrieving file: /am335x-boneblack.dtb
67160 bytes read in 6 ms (10.7 MiB/s)
## Booting kernel from Legacy Image at 82000000 ...
   Image Name:   Linux-5.15.150-yocto-standard
   Created:      2024-03-11  14:54:41 UTC
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    7888296 Bytes = 7.5 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Kernel Image ... OK
   Loading Device Tree to 8ffec000, end 8ffff657 ... OK

Starting kernel ...

Booting Linux on physical CPU 0x0
Linux version 5.15.150-yocto-standard (oe-user@oe-host) (arm-poky-linux-gnueabi-gcc (GCC) 11.4.0, GNU ld (GNU Binutils4
CPU: ARMv7 Processor [413fc082] revision 2 (ARMv7), cr=10c5387d
CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
OF: fdt: Machine model: TI AM335x BeagleBone Black
Memory policy: Data cache writeback
cma: Reserved 16 MiB at 0x9e800000
Zone ranges:
  Normal   [mem 0x0000000080000000-0x000000009fefffff]
  HighMem  empty
Movable zone start for each node
Early memory node ranges
  node   0: [mem 0x0000000080000000-0x000000009fefffff]
Initmem setup node 0 [mem 0x0000000080000000-0x000000009fefffff]
CPU: All CPU(s) started in SVC mode.
AM335X ES2.1 (sgx neon)
Built 1 zonelists, mobility grouping on.  Total pages: 129666
Kernel command line: root=PARTUUID=a607f020-02 rootwait console=ttyS0,115200
Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
mem auto-init: stack:off, heap alloc:off, heap free:off
Memory: 482236K/523264K available (11264K kernel code, 1558K rwdata, 4100K rodata, 1024K init, 328K bss, 24644K reserv)
SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
ftrace: allocating 42062 entries in 124 pages
ftrace: allocated 124 pages with 5 groups
trace event string verifier disabled
rcu: Preemptible hierarchical RCU implementation.
rcu:    RCU event tracing is enabled.
        Trampoline variant of Tasks RCU enabled.
        Rude variant of Tasks RCU enabled.
        Tracing variant of Tasks RCU enabled.
rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
IRQ: Found an INTC at 0x(ptrval) (revision 5.0) with 128 interrupts
TI gptimer clocksource: always-on /ocp/interconnect@44c00000/segment@200000/target-module@31000
sched_clock: 32 bits at 24MHz, resolution 41ns, wraps every 89478484971ns
clocksource: dmtimer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
TI gptimer clockevent: 24000000 Hz at /ocp/interconnect@48000000/segment@0/target-module@40000
Console: colour dummy device 80x30
Calibrating delay loop... 996.14 BogoMIPS (lpj=4980736)
CPU: Testing write buffer coherency: ok
CPU0: Spectre v2: using BPIALL workaround
pid_max: default: 32768 minimum: 301
LSM: Security Framework initializing
landlock: Up and running.
Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
Setting up static identity map for 0x80100000 - 0x80100060
rcu: Hierarchical SRCU implementation.
devtmpfs: initialized
VFP support v0.3: implementor 41 architecture 3 part 30 variant c rev 3
clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
futex hash table entries: 256 (order: -1, 3072 bytes, linear)
pinctrl core: initialized pinctrl subsystem
NET: Registered PF_NETLINK/PF_ROUTE protocol family
DMA: preallocated 256 KiB pool for atomic coherent allocations
thermal_sys: Registered thermal governor 'step_wise'
cpuidle: using governor ladder
cpuidle: using governor menu
hw-breakpoint: debug architecture 0x4 unsupported.
Serial: AMBA PL011 UART driver
kprobes: kprobe jump-optimization is enabled. All kprobes are optimized if possible.
raid6: int32x8  gen()   170 MB/s
raid6: int32x8  xor()   104 MB/s
raid6: int32x4  gen()   199 MB/s
raid6: int32x4  xor()   117 MB/s
raid6: int32x2  gen()   366 MB/s
raid6: int32x2  xor()   202 MB/s
raid6: int32x1  gen()   367 MB/s
raid6: int32x1  xor()   172 MB/s
raid6: using algorithm int32x1 gen() 367 MB/s
raid6: .... xor() 172 MB/s, rmw enabled
raid6: using intx1 recovery algorithm
SCSI subsystem initialized
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
pps_core: LinuxPPS API ver. 1 registered
pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
PTP clock support registered
clocksource: Switched to clocksource dmtimer
NET: Registered PF_INET protocol family
IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
tcp_listen_portaddr_hash hash table entries: 1024 (order: 0, 4096 bytes, linear)
Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
TCP bind hash table entries: 4096 (order: 2, 16384 bytes, linear)
TCP: Hash tables configured (established 4096 bind 4096)
UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
NET: Registered PF_UNIX/PF_LOCAL protocol family
RPC: Registered named UNIX socket transport module.
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
Initialise system trusted keyrings
workingset: timestamp_bits=14 max_order=17 bucket_order=3
NFS: Registering the id_resolver key type
Key type id_resolver registered
Key type id_legacy registered
Key type cifs.idmap registered
xor: measuring software checksum speed
   arm4regs        :  1274 MB/sec
   8regs           :   939 MB/sec
   32regs          :  1273 MB/sec
xor: using function: arm4regs (1274 MB/sec)
Key type asymmetric registered
Asymmetric key parser 'x509' registered
Block layer SCSI generic (bsg) driver version 0.4 loaded (major 248)
io scheduler mq-deadline registered
io scheduler kyber registered
Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
brd: module loaded
mtdoops: mtd device (mtddev=name/number) must be supplied
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ehci-omap: OMAP-EHCI Host Controller driver
usbcore: registered new interface driver usb-storage
SPI driver ads7846 has no spi_device_id for ti,tsc2046
SPI driver ads7846 has no spi_device_id for ti,ads7843
SPI driver ads7846 has no spi_device_id for ti,ads7845
SPI driver ads7846 has no spi_device_id for ti,ads7873
i2c_dev: i2c /dev entries driver
sdhci: Secure Digital Host Controller Interface driver
sdhci: Copyright(c) Pierre Ossman
sdhci-pltfm: SDHCI platform and OF driver helper
usbcore: registered new interface driver usbhid
usbhid: USB HID core driver
u32 classifier
    input device check on
    Actions configured
NET: Registered PF_INET6 protocol family
Segment Routing with IPv6
In-situ OAM (IOAM) with IPv6
sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
NET: Registered PF_PACKET protocol family
Bridge firewalling registered
Key type dns_resolver registered
NET: Registered PF_VSOCK protocol family
ThumbEE CPU extension supported.
omap_voltage_late_init: Voltage driver support not added
Loading compiled-in X.509 certificates
Key type .fscrypt registered
Key type fscrypt-provisioning registered
Btrfs loaded, crc32c=crc32c-generic, zoned=no, fsverity=no
Key type encrypted registered
pinctrl-single 44e10800.pinmux: 142 pins, size 568
ti-sysc: probe of 44e31000.target-module failed with error -16
omap_wdt: OMAP Watchdog Timer Rev 0x01: initial timeout 60 sec
omap_rtc 44e3e000.rtc: already running
omap_rtc 44e3e000.rtc: registered as rtc0
omap_rtc 44e3e000.rtc: setting system clock to 2018-03-09T12:47:45 UTC (1520599665)
ti-sysc: probe of 48040000.target-module failed with error -16
OMAP GPIO hardware version 0.1
omap_i2c 4819c000.i2c: bus 2 rev0.11 at 100 kHz
sdhci-omap 481d8000.mmc: supply vqmmc not found, using dummy regulator
random: crng init done
omap_rng 48310000.rng: Random Number Generator ver. 20
davinci_mdio 4a101000.mdio: davinci mdio revision 1.6, bus freq 1000000
davinci_mdio 4a101000.mdio: phy[0]: device 4a101000.mdio:00, driver SMSC LAN8710/LAN8720
cpsw-switch 4a100000.switch: initialized cpsw ale version 1.4
cpsw-switch 4a100000.switch: ALE Table size 1024
cpsw-switch 4a100000.switch: Detected MACID = 0c:b2:b7:c9:0a:3e
cpsw-switch 4a100000.switch: initialized (regs 0x4a100000, pool size 256) hw_ver:0019010C 1.12 (0)
debugfs: Directory '49000000.dma' with parent 'dmaengine' already present!
edma 49000000.dma: TI EDMA DMA engine driver
am335x-phy-driver 47401300.usb-phy: supply vcc not found, using dummy regulator
am335x-phy-driver 47401300.usb-phy: dummy supplies not allowed for exclusive requests
am335x-phy-driver 47401b00.usb-phy: supply vcc not found, using dummy regulator
am335x-phy-driver 47401b00.usb-phy: dummy supplies not allowed for exclusive requests
hw perfevents: enabled with armv7_cortex_a8 PMU driver, 5 counters available
l3-aon-clkctrl:0000:0: failed to disable
printk: console [ttyS0] disabled
44e09000.serial: ttyS0 at MMIO 0x44e09000 (irq = 18, base_baud = 3000000) is a 8250
printk: console [ttyS0] enabled
tps65217-pmic: Failed to locate of_node [id: -1]
tps65217-bl: Failed to locate of_node [id: -1]
tps65217 0-0024: TPS65217 ID 0xe version 1.2
i2c 0-0070: Fixing up cyclic dependency with 4830e000.lcdc
tda998x 0-0070: found TDA19988
omap_i2c 44e0b000.i2c: bus 0 rev0.11 at 400 kHz
omap_gpio 44e07000.gpio: Could not set line 6 debounce to 200000 microseconds (-22)
tilcdc 4830e000.lcdc: bound 0-0070 (ops tda998x_ops)
sdhci-omap 48060000.mmc: Got CD GPIO
[drm] Initialized tilcdc 1.0.0 20121205 for 4830e000.lcdc on minor 0
sdhci-omap 48060000.mmc: supply vqmmc not found, using dummy regulator
tilcdc 4830e000.lcdc: [drm] Cannot find any crtc or sizes
sdhci-omap 481d8000.mmc: supply vqmmc not found, using dummy regulator
musb-hdrc musb-hdrc.1: MUSB HDRC host driver
musb-hdrc musb-hdrc.1: new USB bus registered, assigned bus number 1
hub 1-0:1.0: USB hub found
hub 1-0:1.0: 1 port detected
printk: console [netcon0] enabled
netconsole: network logging started
mmc0: SDHCI controller on 48060000.mmc [48060000.mmc] using External DMA
cfg80211: Loading compiled-in X.509 certificates for regulatory database
cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
mmc1: SDHCI controller on 481d8000.mmc [481d8000.mmc] using External DMA
cfg80211: Loaded X.509 cert 'wens: 61c038651aabdcf94bd0ac7ff06c7248db18c600'
platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
Waiting for root device PARTUUID=a607f020-02...
cfg80211: failed to load regulatory.db
mmc1: new high speed MMC card at address 0001
mmc0: new high speed SDHC card at address e624
mmcblk1: mmc1:0001 M62704 3.56 GiB 
mmcblk0: mmc0:e624 SS16G 14.8 GiB 
 mmcblk1: p1
mmcblk1boot0: mmc1:0001 M62704 2.00 MiB 
 mmcblk0: p1 p2
mmcblk1boot1: mmc1:0001 M62704 2.00 MiB 
mmcblk1rpmb: mmc1:0001 M62704 512 KiB, chardev (247:0)
EXT4-fs (mmcblk0p2): INFO: recovery required on readonly filesystem
EXT4-fs (mmcblk0p2): write access will be enabled during recovery
EXT4-fs (mmcblk0p2): recovery complete
EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null). Quota mode: disabled.
VFS: Mounted root (ext4 filesystem) readonly on device 179:10.
devtmpfs: mounted
Freeing unused kernel image (initmem) memory: 1024K
Run /sbin/init as init process
INIT: version 3.01 booting
FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
Starting udev
udevd[135]: starting version 3.2.10
udevd[136]: starting eudev-3.2.10
EXT4-fs (mmcblk0p2): re-mounted. Opts: (null). Quota mode: disabled.
INIT: Entering runlevel: 5
Configuring network interfaces... cpsw-switch 4a100000.switch: starting ndev. mode: dual_mac
SMSC LAN8710/LAN8720 4a101000.mdio:00: attached PHY driver (mii_bus:phy_addr=4a101000.mdio:00, irq=POLL)
udhcpc: started, v1.35.0
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: no lease, forking to background
done.
Starting OpenBSD Secure Shell server: sshd
done.
Starting rpcbind daemon...done.
starting statd: done
Starting atd: OK
NFS daemon support not enabled in kernel
Starting system log daemon...0
Starting crond: OK

Poky (Yocto Project Reference Distro) 4.0.21 beaglebone-yocto ttyS0

beaglebone-yocto login: `

**Comment by Munawar-git** [comment]
May be problem with your serial connection.

**Comment by Munawar-git** [comment]
user name is root.

**Comment by viveky1794** [comment]
Currently I am using Ubuntu machine 20.04 where this serial converter is not working. Whereas when I connect with putty. It works well.
Now I am able to login as well.

**Comment by viveky1794** [comment]
I figured out what was the issue with my minicom (serial app) in Ubuntu (20.04 and 22.04).
By default `Hardware flow control` set as `YES` . So change it and set as  `NO`.
